#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
then
    sudo service nginx restart
else
    sudo service nginx start
fi
