#!/usr/bin/env bash
# This script is used for FizzBuzz game
# Displays numbers from 1 to 100 in list format.
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

count=1

while [ "$count" -le 100 ]; do


  if ! (( count % 3 )) && ! (( count % 5 )); then
    echo "FizzBuzz"
  elif ! (( count % 3 )); then
    echo "Fizz"
  elif ! (( count % 5 )); then
    echo "Buzz"
  else
    echo "$count"
  fi

  ((count++))
done