#!/usr/bin/env bash
# 4 bad luck, 8 is your chance

count=1

while [ "$count" -lt 11 ]; do

  # if 4 bad luck elif 8 good luck
  if [ "$count" -eq 4 ]; then
    echo "bad luck"
  elif [ "$count" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((count++))
done