#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
#   "bad luck from China" for the 4th iteration
#   "bad luck from Japan" for the 9th iteration
#   "bad luck from Italy" for the 17th loop iteration

count=1

while [ "$count" -lt 21 ]; do

  case "$count" in
    4)
      echo "$count"
      echo "bad luck from China"
      ;;
    9)
      echo "$count"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$count"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$count"
      ;;
  esac

  ((count++))
done